TOEIC_SaoKhue/Models/GIAOVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class GIAOVIEN
    {
        public short MaGV { get; set; }
        public string TenGV { get; set; }
        public string SDTGV { get; set; }
    }
}

TOEIC_SaoKhue/Models/LICHSUDAY.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class LICHSUDAY
    {
        public string MaLop { get; set; }
        public string MaCT { get; set; }
        public Nullable<short> MaCH { get; set; }
        public string CaHoc { get; set; }
        public short GioiHan { get; set; }
        public short SiSo { get; set; }
        public System.DateTime NgayKhaiGiang { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
    }
}

TOEIC_SaoKhue/Controllers/GiaoVienController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOEIC_SaoKhue.Models;

namespace TOEIC_SaoKhue.Controllers
{
    [Auth(Roles = "NhanVien")]
    public class GiaoVienController : Controller
    {
        // GET: GiaoVien
        public ActionResult Index()
        {            
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.GiaoViens = db.sp_LietKeGiaoVien().ToList();

                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        public ActionResult LichSuDay(short? giaovien, short? trang)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.GiaoVien = db.sp_XemGiaoVien(giaovien).FirstOrDefault();
                    if (ViewBag.GiaoVien == null)
                        return View();
                    short k = 1;
                    if (trang != null) { try { k = trang.GetValueOrDefault(); if (k < 1) { k = 1; } } catch { k = 1; } }
                    ViewBag.Lops = db.sp_XemLichSuDay(giaovien, 30, k).ToList();
                    ViewBag.KeTiep = db.sp_XemLichSuDay(giaovien, 30, (short?)(k + 1)).Count();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }            
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Them(string ten, string sdt)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_ThemGiaoVien(ten, sdt);

                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Xoa(short magv)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_XoaGiaoVien((short?)magv);

                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult CapNhat(short magv, string ten, string sdt)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_CapNhatGiaoVien((short?)magv, ten, sdt);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }
    }
}

TOEIC_SaoKhue/Controllers/LopController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOEIC_SaoKhue.Models;

namespace TOEIC_SaoKhue.Controllers
{
    [Auth(Roles = "NhanVien")]
    public class LopController : Controller
    {
        // GET: Lop
        public ActionResult Index(short? loc, string chuongtrinh, short? trang)
        {
            try
            {
                using (Entities db = new Entities())
                {      
                    if (chuongtrinh == null)
                        chuongtrinh = "";
                    short k = 1;
                    if (trang != null) { try { k = trang.GetValueOrDefault(); if (k < 1) { k = 1; } } catch { k = 1; } }
                    ViewBag.ChuongTrinhs = db.sp_LietKeChuongTrinh().ToList();
                    ViewBag.Lops = db.sp_TimLop(chuongtrinh, loc, 20, k).ToList();
                    ViewBag.KeTiep = db.sp_TimLop(chuongtrinh, loc, 20, (short?)(k + 1)).Count();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }           
        }

        public ActionResult Xem(string lop)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.Lop = db.sp_XemLop(lop).FirstOrDefault();
                    if (ViewBag.Lop == null)
                    {
                        return View();
                    }
                    ViewBag.GiaoViens = db.sp_LietKeGiaoVien().ToList();
                    ViewBag.HocViens = db.sp_XemDanhSachLop(lop).ToList();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }            
        }

        [Auth(Roles = "QuanLy")]
        public ActionResult Them()
        {
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.ChuongTrinhs = db.sp_LietKeChuongTrinh().ToList();
                    ViewBag.CaHocs = db.sp_LietKeCaHoc().ToList();
                    ViewBag.GiaoViens = db.sp_LietKeGiaoVien().ToList();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }            
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Them_2(string chuongtrinh, int cahoc, int giaovien, int gioihan, DateTime? khaigiang, DateTime? ketthuc)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_ThemLop(chuongtrinh, (short?)cahoc, (short?)giaovien, (short?)gioihan, khaigiang, ketthuc);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Xoa(string lop)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_HuyLop(lop);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [HttpPost]
        public ActionResult Tim(string malop)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    LOP lop = db.sp_XemLop(malop).FirstOrDefault();
                    if (lop == null)
                        return Json(new { success = false }, JsonRequestBehavior.DenyGet);
                    string thoigianhoc = lop.NgayKhaiGiang.ToShortDateString() + " - " + lop.NgayKetThuc.ToShortDateString();
                    return Json(new { success = true, malop = lop.MaLop, thoigianhoc, hocphi = lop.HocPhiCT }, JsonRequestBehavior.DenyGet);
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "GiaoVien")]
        public ActionResult ChamDiem(string lop)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.Lop = db.sp_XemLop(lop).ToList();
                    ViewBag.HocViens = db.sp_DanhSachChamDiem(lop).ToList();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "GiaoVien")]
        [HttpPost]
        public ActionResult ChamDiem_2(int? mahd, string malop, string diemchuyencan, string diemcuoiky)
        {
            short chuyencan, cuoiky;
            try
            {
                chuyencan = short.Parse(diemchuyencan);
                cuoiky = short.Parse(diemcuoiky);
            }
            catch {
                return Json(new { success = false, msg = "Điểm không hợp lệ" }, JsonRequestBehavior.DenyGet);
            }
            try
            {
                using (Entities db = new Entities())
                {
                    try                    {
                        db.sp_ChamDiem(mahd, malop, chuyencan, cuoiky);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {
                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }            
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult BoTriGiaoVien(string malop, short magv)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_BoTriGiaoVien(malop, magv);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {
                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }
    }
}

TOEIC_SaoKhue/Views/GiaoVien/Index.cshtml
@{
    ViewBag.Title = "Danh sách giáo viên";
}

<div>
    @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "A")
    {
    <div style="margin-bottom: 20px;" class="text-center">
        <form class="form-inline" id="them-gv">
            <input name="ten" placeholder="Tên giáo viên" class="form-control" />
            <input name="sdt" placeholder="Số điện thoại" class="form-control" />
            <input type="submit" class="btn btn-primary" value="Thêm giáo viên" />
        </form>
        <form class="form-inline" id="capnhat-gv" style="display: none;">
            <input name="magv" id="capnhat-magv" class="form-control" style="width: 90px" readonly/>
            <input name="ten" placeholder="Tên giáo viên" class="form-control" id="capnhat-tengv"/>
            <input name="sdt" placeholder="Số điện thoại" class="form-control" id="capnhat-sdtgv"/>
            <input type="submit" class="btn btn-success" value="Cập nhật" />
            <a href="@Url.Action("Index", "GiaoVien")" class="btn btn-danger">Hủy</a>
        </form>
    </div>
    }
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Họ tên</th>
                <th>Số điện thoại</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (TOEIC_SaoKhue.Models.GIAOVIEN item in ViewBag.GiaoViens)
            {
                <tr>
                    <td>@item.MaGV</td>
                    <td>@item.TenGV</td>
                    <td>@item.SDTGV</td>
                    <td class="text-right">
                        <table style="width: auto; margin-right: 0px; margin-left: auto;">
                            <tr>
                                <td style="padding-left: 10px">
                                    <a class="btn btn-info" href="@Url.Action("LichSuDay", "GiaoVien", new { giaovien = item.MaGV })">Lịch sử dạy học</a>
                                </td>

                                @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "A")
                                {
                                    <td style="padding-left: 10px">
                                        <button class="btn btn-warning capnhat-gv" value="@item.MaGV|@item.TenGV|@item.SDTGV">Cập nhật</button>
                                    </td>
                                    <td style="padding-left: 10px">
                                        <form class="xoa-gv">
                                            <input type="hidden" name="magv" value="@item.MaGV" />
                                            <input type="submit" class="btn btn-danger" value="Xóa" />
                                        </form>
                                    </td>
                                    }
                                </tr>
                        </table>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TOEIC_SaoKhue/Views/GiaoVien/LichSuDay.cshtml
@{
    ViewBag.Title = "Lịch sử dạy";
}

<div style="margin-bottom: 20px">
    <a href="@Url.Action("Index", "GiaoVien")" class="btn btn-primary">Quay về danh sách giáo viên</a>
</div>
@if (ViewBag.GiaoVien == null)
{
    <div class="text-center">
        <h4>Không tìm thấy giáo viên @Request.QueryString["giaovien"]</h4>
        <h5>Vui lòng kiểm tra lại mã giáo viên hoặc quay về danh sách giáo viên</h5>
    </div>
}
else
{
<div>
    <div class="row">
        <div class="col-xs-3"><b>Mã giáo viên: </b>@ViewBag.GiaoVien.MaGV</div>
        <div class="col-xs-9"><b>Họ tên: </b>@ViewBag.GiaoVien.TenGV</div>
    </div>
    <table class="table table-hover" style="margin-top: 20px">
        <thead>
            <tr>
                <th>Mã lớp</th>
                <th>Ca học</th>
                <th>Sĩ số</th>
                <th>Ngày khai giảng</th>
                <th>Ngày kết thúc</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (TOEIC_SaoKhue.Models.LICHSUDAY items in ViewBag.Lops)
            {
                <tr>
                    <td>@items.MaLop</td>
                    <td>
                        @if (items.MaCH != null) { 
                            <span>@items.CaHoc</span>
                        }
                    </td>
                    <td>@items.SiSo / @items.GioiHan</td>
                    <td>@items.NgayKhaiGiang</td>
                    <td>@items.NgayKetThuc</td>
                    <td class="text-right">
                        <a href="@Url.Action("Xem","Lop",new { lop = items.MaLop })" class="btn btn-info">Chi tiết</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @{
            short k = 1;
            try { k = short.Parse(Request.QueryString["trang"]); } catch { } }
        <div class="text-center">
            <div class="btn-group">
                @if (k > 1)
                {
                    <a href="@Url.Action("LichSuDay","GiaoVien", new { giaovien = Request.QueryString["giaovien"], trang = k - 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span></a>
                }
                @if (ViewBag.KeTiep > 0)
                {
                    <a href="@Url.Action("LichSuDay","GiaoVien", new { giaovien = Request.QueryString["giaovien"], trang = k + 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-forward"></span></a>
                }
            </div>
        </div>
    </div>
</div>
}