TOEIC_SaoKhue/Models/HOADON.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class HOADON
    {
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaHV { get; set; }
        public string TenHV { get; set; }
        public string SDTHV { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<double> HocPhiDong { get; set; }
    }
}

TOEIC_SaoKhue/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOEIC_SaoKhue.Models;

namespace TOEIC_SaoKhue.Controllers
{
    [Auth(Roles = "NhanVien")]
    public class HoaDonController : Controller
    {
        // GET: HoaDon
        public ActionResult Index(string sdt, short? trang)
        {
            short k = 1;
            if (trang != null) { try { k = trang.GetValueOrDefault(); if (k < 1) { k = 1; } } catch { k = 1; } }
            if (sdt == null)
            {
                sdt = "";
            }
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.HoaDons = db.sp_TimHoaDon(sdt, 20, k).ToList();
                    ViewBag.KeTiep = db.sp_TimHoaDon(sdt, 20, (short?)(k + 1)).Count();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "TuVan")]
        public ActionResult LapHoaDon()
        {
            return View();
        }
        
        public ActionResult Xem(int? hoadon)
        {            
            try
            {
                using (Entities db = new Entities())
                {
                    HOADON _hoadon = db.sp_XemHoaDon(hoadon).FirstOrDefault();
                    if (_hoadon == null)
                    {
                        return View();
                    }
                    ViewBag.HoaDon = _hoadon;
                    ViewBag.Lops = db.sp_XemCacLopHoaDon(hoadon).ToList();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "TuVan")]
        [HttpPost]
        public ActionResult LapHoaDon_2(int? hocvien, string lops, string dks)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        lops = lops.Replace(" ", "");
                        int? mahd = db.sp_DongHocPhi(hocvien, lops, dks).FirstOrDefault();
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }
    }
}

TOEIC_SaoKhue/Views/HoaDon/Index.cshtml
@{
    ViewBag.Title = "Danh sách hóa đơn";
}

<div>
    @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "B")
    {
    <div class="row">
        <div class="col-xs-9">
            <form class="form-inline" action="@Url.Action("Index", "HoaDon")">
                <input type="text" name="sdt" class="form-control" placeholder="Số điện thoại học viên" />
                <input type="submit" value="Tìm" class="btn btn-primary" />
            </form>
        </div>
        <div class="col-xs-3 text-right">
            <a href="@Url.Action("LapHoaDon", "HoaDon")" class="btn btn-primary">Lập hóa đơn</a>
        </div>
    </div>}
    <div>
        <table class="table table-hover" style="margin-top: 20px">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Học viên</th>
                    <th>Số điện thoại</th>
                    <th>Ngày lập</th>
                    <th>Tổng</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (TOEIC_SaoKhue.Models.HOADON item in ViewBag.HoaDons)
                {
                    <tr>
                        <td>
                            @item.MaHD
                        </td>
                        <td>
                            @item.TenHV
                        </td>
                        <td>
                            @item.SDTHV
                        </td>
                        <td>
                            @item.NgayLapHD.GetValueOrDefault().ToShortDateString()
                        </td>
                        <td>
                            @item.HocPhiDong.GetValueOrDefault().ToString("N0") vnđ
                        </td>
                        <td class="text-right">
                            <a href="@Url.Action("Xem","HoaDon", new { hoadon = item.MaHD })" class="btn btn-info">Chi tiết</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @{
                short k = 1;
                try { k = short.Parse(Request.QueryString["trang"]); } catch { } }
            <div class="text-center">
                <div class="btn-group">
                    @if (k > 1)
                    {
                        <a href="@Url.Action("Index","HoaDon", new { sdt = Request.QueryString["sdt"], trang = k - 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span></a>
                    }
                    @if (ViewBag.KeTiep > 0)
                    {
                        <a href="@Url.Action("Index","HoaDon", new { sdt = Request.QueryString["sdt"], trang = k + 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-forward"></span></a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TOEIC_SaoKhue/Views/HoaDon/LapHoaDon.cshtml
@{
    ViewBag.Title = "LapHoaDon";
}

<div>
    <div class="text-center">
        <h3>Lập hóa đơn</h3>
    </div>
    <form style="margin-top: 30px" id="laphd">
        <div class="form-group row">
            <label for="hocvien" class="col-xs-4">Học viên</label>
            <div class="col-xs-8">
                <input name="hocvien" placeholder="Mã học viên" class="form-control" id="hoadon-mahv" />
                <div id="hoadon-hocvien" style="margin-top: 10px; display: none;">
                    <p>
                        <i>Tên học viên:</i> <span id="hoadon-tenhv"></span>
                    </p>
                    <p>
                        <i>Số điện thoại:</i> <span id="hoadon-sdthv"></span>
                    </p>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="lops" class="col-xs-4">Lớp</label>
            <div class="col-xs-8">
                <input name="lops" placeholder="Mã lớp 1, Mã lớp 2, ..." class="form-control" id="hoadon-malop" />
            </div>
        </div>
        <div class="form-group row">
            <label for="lops" class="col-xs-4">Đăng ký:</label>
            <div class="col-xs-8">
                <input name="dks" placeholder="Mã đăng ký 1, Mã đăng ký 2, ..." class="form-control" id="hoadon-madk" />
            </div>
        </div>
        <table class="table table-bordered" style="margin-top: 10px">
            <thead>
                <tr>
                    <th>
                        Mã lớp
                    </th>
                    <th>
                        Thời gian học
                    </th>
                    <th>
                        Học phí
                    </th>
                </tr>
            </thead>
            <tbody id="hoadon-lops">
            </tbody>
        </table>
        <div class="form-group text-center">
            <div class="btn-group">
                <a href="@Url.Action("Index", "HoaDon")" class="btn btn-danger">Hủy</a>
                <input type="submit" class="btn btn-success" value="Đã thu học phí" id="hoadon-submit" />
            </div>
        </div>
    </form>
</div>

TOEIC_SaoKhue/Views/HoaDon/ThuHocPhiDangKy.cshtml
@{
    ViewBag.Title = "Thu học phí";
}

<div>
    <div>
        <h4>Thu học phí cho lớp:</h4>
        <table class="table table-bordered">
            <tr>
                <th>Mã lớp</th>
                <td>@ViewBag.Lop.MaLop</td>
            </tr>
            <tr>
                <th>Chương trình</th>
                <td>@ViewBag.Lop.CHUONGTRINH.TenCT</td>
            </tr>
            <tr>
                <th>Độ dài của lớp học</th>
                <td>
                    @ViewBag.Lop.CHUONGTRINH.ThoiGianHoc<br /> @ViewBag.Lop.NgayKhaiGiang.ToShortDateString() - @ViewBag.Lop.NgayKetThuc.ToShortDateString()
                </td>
            </tr>
            <tr>
                <th>Học phí</th>
                <td>@ViewBag.Lop.CHUONGTRINH.HocPhiCT.ToString("N0") VNĐ</td>
            </tr>
            <tr>
                <th>Ca học</th>
                <td>
                    @if (ViewBag.Lop.CAHOC != null)
                    {<span>@ViewBag.Lop.CAHOC.NgayHoc @ViewBag.Lop.CAHOC.GioHoc</span>}
                </td>
            </tr>
            <tr>
                <th>Giáo viên</th>
                <td>
                    @if (ViewBag.Lop.GIAOVIEN != null)
                    {<span>@ViewBag.Lop.GIAOVIEN.TenGV</span>}
                </td>
            </tr>
        </table>
    </div>
    <div class="text-center">
        <form class="form-inline" id="thu_hocphidk">
            <input name="sdt" type="hidden" value="@ViewBag.SDT" />
            <input name="stt" type="hidden" value="@ViewBag.STT" />
            <input name="lop" type="hidden" value="@ViewBag.Lop.MaLop" />
            <input name="mahv" class="form-control" placeholder="Mã học viên" />
            <input name="hocphi" class="form-control" placeholder="Học phí" type="number" value="@ViewBag.Lop.CHUONGTRINH.HocPhiCT" readonly/>
            <input type="submit" class="btn btn-primary" value="Đã thu học phí" />
        </form>
    </div>
</div>

TOEIC_SaoKhue/Views/HoaDon/Xem.cshtml
@{
    ViewBag.Title = "Chi tiết hóa đơn";
}

<div style="margin-bottom: 20px">
    <a href="@Url.Action("Index", "HoaDon")" class="btn btn-primary">Quay về danh sách hóa đơn</a>
</div>
@if (ViewBag.HoaDon == null)
{
    <div class="text-center">
        <h4>Không tìm thấy hóa đơn @Request.QueryString["hoadon"]</h4>
        <h5>Vui lòng kiểm tra lại mã hóa đơn hoặc quay về danh sách hóa đơn</h5>
    </div>
}
else
{
<div>
    <div class="text-center"><h3>Thông tin hóa đơn</h3></div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Mã hóa đơn</b>
        </div>
        <div class="col-xs-9">
            @ViewBag.HoaDon.MaHD
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Ngày lập hóa đơn</b>
        </div>
        <div class="col-xs-9">
            @ViewBag.HoaDon.NgayLapHD.ToShortDateString()
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Học viên</b>
        </div>
        <div class="col-xs-9">
            @ViewBag.HoaDon.TenHV
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Số điện thoại</b>
        </div>
        <div class="col-xs-9">
            @ViewBag.HoaDon.SDTHV
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Học phí</b>
        </div>
        <div class="col-xs-9">
            @ViewBag.HoaDon.HocPhiDong.ToString("N0") vnđ
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-3">
            <b>Lớp</b>
        </div>
        <div class="col-xs-9">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Mã lớp</th>
                        <th>Giáo viên</th>
                        <th>Ngày học</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (TOEIC_SaoKhue.Models.LOP item in ViewBag.Lops) { 
                    <tr>
                        <td>
                            @item.MaLop
                        </td>
                        <td>
                            @item.TenGV
                        </td>
                        <td>
                            @item.NgayKhaiGiang.ToShortDateString() - @item.NgayKetThuc.ToShortDateString()
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>    
</div>
}