TOEIC_SaoKhue/Models/HOCVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class HOCVIEN
    {
        public Nullable<int> MaHV { get; set; }
        public string TenHV { get; set; }
        public string SDTHV { get; set; }
        public string EmailHV { get; set; }
    }
}

TOEIC_SaoKhue/Controllers/HocVienController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOEIC_SaoKhue.Models;

namespace TOEIC_SaoKhue.Controllers
{
    [Auth(Roles = "NhanVien")]
    public class HocVienController : Controller
    {
        // GET: HocVien
        public ActionResult Index(string sdt, short? trang)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    if (sdt == null)
                        sdt = "";
                    short k = 1;
                    if (trang != null) { try { k = trang.GetValueOrDefault(); if (k < 1) { k = 1; } } catch { k = 1; } }
                    ViewBag.HocViens = db.sp_TimHocVien(sdt, 20, k).ToList();
                    ViewBag.KeTiep = db.sp_TimHocVien(sdt, 20, (short?)(k + 1)).Count();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }            
        }

        [Auth(Roles = "TuVan")]
        [HttpPost]
        public ActionResult Them(string hoten, string sdt, string email)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_ThemHocVien(hoten, sdt, email);
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {

                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        public ActionResult Xem(int? hocvien)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    int mahv = 0;
                    try { mahv = hocvien.GetValueOrDefault(); } catch { }
                    ViewBag.HocVien = db.sp_XemHocVien(hocvien).FirstOrDefault();
                    if (ViewBag.HocVien == null)
                    {
                        return View();
                    }
                    ViewBag.LichSuHocs = db.sp_XemLichSuHoc(hocvien).ToList();
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [HttpPost]
        public ActionResult Tim(int? mahv)
        {            
            try
            {
                using (Entities db = new Entities())
                {
                    HOCVIEN hocvien = db.sp_XemHocVien(mahv).FirstOrDefault();
                    if (hocvien == null)
                        return Json(new { success = false }, JsonRequestBehavior.DenyGet);
                    return Json(new { success = true, tenhv = hocvien.TenHV, sdt = hocvien.SDTHV }, JsonRequestBehavior.DenyGet);
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }
    }
}

TOEIC_SaoKhue/Views/HocVien/Index.cshtml
@{
    ViewBag.Title = "Danh sách học viên";
}

<div class="row">
    @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "B")
    {
    <div style="margin-bottom: 20px">
        <form style="margin-bottom: 20px" class="form-inline" action="@Url.Action("Index", "HocVien")">
            <input type="text" name="sdt" class="form-control" placeholder="Số điện thoại" />
            <input type="submit" value="Tìm" class="btn btn-primary" />
        </form>
    </div>
    <div style="margin-bottom: 20px">
        <form class="form-inline" id="themhv">
            <input name="hoten" class="form-control" placeholder="Họ tên" style="max-width: 300px; width: 300px"/>
            <input name="sdt" class="form-control" placeholder="Số điện thoại" style="max-width: 300px; width: 300px" />
            <input name="email" class="form-control" placeholder="Email" style="max-width: 300px; width: 300px"/>
            <input type="submit" value="Thêm học viên" class="btn btn-default"/>
        </form> 
    </div>}
    <div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Họ tên</th>
                    <th>Số điện thoại</th>
                    <th>Email</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (TOEIC_SaoKhue.Models.HOCVIEN item in ViewBag.HocViens)
                {
                    <tr>
                        <td>
                            @item.MaHV
                        </td>
                        <td>
                            @item.TenHV
                        </td>
                        <td>
                            @item.SDTHV
                        </td>
                        <td>
                            @item.EmailHV
                        </td>
                        <td class="text-right">
                            <a href="@Url.Action("Xem", "HocVien", new { hocvien = item.MaHV })" class="btn btn-info">Chi tiết</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @{
                short k = 1;
                try { k = short.Parse(Request.QueryString["trang"]); } catch { } }
            <div class="text-center">
                <div class="btn-group">
                    @if (k > 1)
                    {
                        <a href="@Url.Action("Index","HocVien", new { sdt = Request.QueryString["sdt"], trang = k - 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span></a>
                    }
                    @if (ViewBag.KeTiep > 0)
                    {
                        <a href="@Url.Action("Index","HocVien", new { sdt = Request.QueryString["sdt"], trang = k + 1 })" class="btn btn-primary"><span class="glyphicon glyphicon-forward"></span></a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TOEIC_SaoKhue/Views/HocVien/Xem.cshtml
@{
    ViewBag.Title = "Thông tin lớp";
}


<div style="margin-bottom: 20px">
    <a href="@Url.Action("Index", "HocVien")" class="btn btn-primary">Quay về danh sách học viên</a>
</div>
@if (ViewBag.HocVien == null)
{
    <div class="text-center">
        <h4>Không tìm thấy học viên @Request.QueryString["lop"]</h4>
        <h5>Vui lòng kiểm tra lại mã học viên hoặc quay về danh sách học viên</h5>
    </div>
}
else
{
    <div>
        <div class="text-center"><h3>Thông tin học viên</h3></div>
        <table class="table table-bordered">
            <tr>
                <th>Họ tên</th>
                <td>@ViewBag.HocVien.TenHV</td>
            </tr>
            <tr>
                <th>Số điện thoại</th>
                <td>
                    @ViewBag.HocVien.SDTHV
                </td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@ViewBag.HocVien.EmailHV</td>
            </tr>
        </table>
        <div class="text-center" style="margin-top: 20px">
            <h3>Học bạ</h3>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">Mã lớp</th>
                        <th class="text-center">Điểm chuyên cần</th>
                        <th class="text-center">Điểm cuối kỳ</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (TOEIC_SaoKhue.Models.LICHSUHOC item in ViewBag.LichSuHocs) { 
                    <tr>
                        <td>
                            @item.MaLop
                        </td>
                        <td>@item.DiemChuyenCan</td>
                        <td>@item.DiemCuoiKy</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}