TOEIC_SaoKhue/Models/CAHOC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class CAHOC
    {
        public short MaCH { get; set; }
        public string GioHoc { get; set; }
        public string NgayHoc { get; set; }
    }
}

TOEIC_SaoKhue/Controllers/CaHocController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOEIC_SaoKhue.Models;

namespace TOEIC_SaoKhue.Controllers
{
    [Auth(Roles = "NhanVien")]
    public class CaHocController : Controller
    {
        // GET: CaHoc
        public ActionResult Index()
        {
            try
            {
                using (Entities db = new Entities())
                {
                    ViewBag.CaHocs = db.sp_LietKeCaHoc().ToList();                    
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Them(string giohoc, string ngayhoc)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_ThemCaHoc(giohoc, ngayhoc);
                        
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {
                        
                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult Xoa(short mach)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_XoaCaHoc((short?)mach);
                        
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {
                        
                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }

        [Auth(Roles = "QuanLy")]
        [HttpPost]
        public ActionResult CapNhat(short mach, string giohoc, string ngayhoc)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    try
                    {
                        db.sp_CapNhatCaHoc(mach, giohoc, ngayhoc);
                        
                        return Json(new { success = true }, JsonRequestBehavior.DenyGet);
                    }
                    catch (Exception e)
                    {
                        
                        SqlException sqlex = e.InnerException as SqlException;
                        return Json(new { success = false, msg = sqlex.Message }, JsonRequestBehavior.DenyGet);
                    }
                }
            }
            catch
            {
                return RedirectToAction("DangNhap", "TaiKhoan");
            }
        }
    }
}

TOEIC_SaoKhue/Views/CaHoc/Index.cshtml
@{
    ViewBag.Title = "Các ca học";
}

<div>
    @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "A")
    { 
    <div style="margin-bottom: 20px;" class="text-center">
        <form class="form-inline" id="them-ch">
            <input name="giohoc" placeholder="Giờ học" class="form-control" />
            <input name="ngayhoc" placeholder="Ngày học" class="form-control" />
            <input type="submit" class="btn btn-primary" value="Thêm ca học" />
        </form>
        <form class="form-inline" id="capnhat-ch" style="display: none;">
            <input name="mach" type="hidden" id="capnhat-ch-mach" />
            <input name="giohoc" placeholder="Giờ học" class="form-control" id="capnhat-ch-giohoc" />
            <input name="ngayhoc" placeholder="Ngày học" class="form-control" id="capnhat-ch-ngayhoc" />
            <input type="submit" class="btn btn-success" value="Cập nhật" />
            <a href="@Url.Action("Index","CaHoc")" class="btn btn-danger">Hủy</a>
        </form>
    </div>
    }    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Giờ học</th>
                <th>Ngày học</th>
                @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "A")
                {<th></th>}
            </tr>
        </thead>
        <tbody>
            @foreach (TOEIC_SaoKhue.Models.CAHOC item in ViewBag.CaHocs)
            {
                <tr>
                    <td>@item.MaCH</td>
                    <td>@item.GioHoc</td>
                    <td>@item.NgayHoc</td>
                    @if (Session["taikhoan"] != null && ((TOEIC_SaoKhue.Models.TAIKHOAN)Session["taikhoan"]).LoaiTK == "A") { 
                    <td class="text-right">
                        <table style="width: auto; margin-right: 0px; margin-left: auto;">
                            <tr>
                                <td>
                                    <button class="btn btn-warning capnhat-ch" value="@item.MaCH|@item.GioHoc|@item.NgayHoc" id="btn-capnhat-ch">Cập nhật</button>
                                </td>
                                <td style="padding-left: 10px">
                                    <form class="xoa-ch">
                                        <input type="hidden" name="mach" value="@item.MaCH" />
                                        <input type="submit" class="btn btn-danger" value="Xóa" />
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </td>
                    }                    
                </tr>
            }
        </tbody>
    </table>
</div>